# Generated by Django 4.2.30 on 2026-05-23 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('niche', models.CharField(max_length=300, verbose_name='Nicho/Produto')),
                ('whatsapp', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Número de WhatsApp inválido. Use o formato: (34) 99999-9999', regex='^(\\+?55\\s?)?(\\(?\\d{2}\\)?\\s?)?9?\\d{4}-?\\d{4}$')], verbose_name='WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('price_range', models.CharField(choices=[('29', 'R$29/mês'), ('49', 'R$49/mês'), ('99', 'R$99/mês'), ('annual', 'Pagaria plano anual com desconto'), ('free_first', 'Só testaria grátis primeiro'), ('other', 'Outro')], max_length=20, verbose_name='Faixa de Preço')),
                ('main_difficulty', models.TextField(blank=True, help_text='Qual sua maior dificuldade hoje para encontrar produtos com potencial de venda?', null=True, verbose_name='Principal Dificuldade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
