# Generated by Django 4.2.30 on 2026-05-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='price_range',
            field=models.CharField(blank=True, choices=[('29', 'R$29/mês'), ('49', 'R$49/mês'), ('99', 'R$99/mês'), ('annual', 'Pagaria plano anual com desconto'), ('free_first', 'Só testaria grátis primeiro'), ('other', 'Outro')], max_length=20, null=True, verbose_name='Faixa de Preço'),
        ),
    ]
