# Generated by Django 4.2.30 on 2026-05-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_lead_email_alter_lead_price_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='niche',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nicho/Produto'),
        ),
    ]
