# Generated by Django 4.2.30 on 2026-05-26 17:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_lead_name_alter_lead_niche'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Número de WhatsApp inválido. Use o formato: (34) 99999-9999', regex='^(\\+?55\\s?)?(\\(?\\d{2}\\)?\\s?)?9?\\d{4}-?\\d{4}$')], verbose_name='WhatsApp')),
                ('normalized_whatsapp', models.CharField(db_index=True, help_text='Somente dígitos para lookup', max_length=20, verbose_name='WhatsApp Normalizado')),
                ('has_used_free_test', models.BooleanField(default=False, verbose_name='Usou Teste Grátis')),
                ('free_test_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Data do Teste Grátis')),
                ('analyzed_product', models.CharField(blank=True, max_length=200, null=True, verbose_name='Produto Analisado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Session Key')),
                ('submitted_feedback', models.BooleanField(default=False, verbose_name='Enviou Feedback')),
                ('joined_waitlist', models.BooleanField(default=False, verbose_name='Entrou na Lista')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'WhatsApp Lead',
                'verbose_name_plural': 'WhatsApp Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['normalized_whatsapp'], name='landing_wha_normali_f4bd6c_idx'), models.Index(fields=['has_used_free_test'], name='landing_wha_has_use_d6fc9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalysisFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_query', models.CharField(max_length=200, verbose_name='Produto Analisado')),
                ('rating', models.CharField(choices=[('very_useful', 'Muito útil'), ('interesting', 'Interessante'), ('confusing', 'Confuso'), ('not_trust', 'Não confiaria'), ('would_use_again', 'Usaria novamente')], max_length=20, verbose_name='Avaliação')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentários')),
                ('would_pay', models.BooleanField(default=False, verbose_name='Pagaria por isso')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('whatsapp_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='landing.whatsapplead')),
            ],
            options={
                'verbose_name': 'Feedback de Análise',
                'verbose_name_plural': 'Feedbacks de Análise',
                'ordering': ['-created_at'],
            },
        ),
    ]
