# Generated by Django 4.2.30 on 2026-05-26 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_whatsapplead_analysisfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapplead',
            name='whatsapp',
            field=models.CharField(error_messages={'unique': 'Esse WhatsApp já utilizou a análise gratuita.'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Número de WhatsApp inválido. Use o formato: (34) 99999-9999', regex='^(\\+?55\\s?)?(\\(?\\d{2}\\)?\\s?)?9?\\d{4}-?\\d{4}$')], verbose_name='WhatsApp'),
        ),
    ]
