# Generated by Django 4.2.30 on 2026-05-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_alter_whatsapplead_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisfeedback',
            name='would_pay',
        ),
        migrations.AddField(
            model_name='analysisfeedback',
            name='confidence_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nível de Confiança (%)'),
        ),
        migrations.AddField(
            model_name='analysisfeedback',
            name='entered_waitlist',
            field=models.BooleanField(default=False, verbose_name='Entrou na lista de espera'),
        ),
        migrations.AddField(
            model_name='analysisfeedback',
            name='product_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Score Final'),
        ),
        migrations.AddField(
            model_name='analysisfeedback',
            name='would_pay_for_analyses',
            field=models.BooleanField(default=False, verbose_name='Pagaria por análises assim'),
        ),
    ]
