# Generated by Django 4.2.30 on 2026-05-28 (Manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_remove_analysisfeedback_would_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapplead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='whatsapplead',
            name='unlocked_analysis',
            field=models.BooleanField(default=False, verbose_name='Desbloqueou Análise'),
        ),
        migrations.AddField(
            model_name='whatsapplead',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desbloqueado em'),
        ),
        migrations.AddField(
            model_name='whatsapplead',
            name='willingness_to_pay',
            field=models.CharField(blank=True, choices=[('yes', 'Sim, pagaria'), ('maybe', 'Talvez'), ('no', 'Não pagaria')], max_length=10, null=True, verbose_name='Pagaria pelo produto'),
        ),
        migrations.AddField(
            model_name='whatsapplead',
            name='launch_interest',
            field=models.BooleanField(default=False, verbose_name='Quer saber do lançamento'),
        ),
    ]
