# Generated by Django 4.2.30 on 2026-05-28 (Manual)

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_whatsapplead_new_conversion_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapplead',
            name='whatsapp',
            field=models.CharField(blank=True, default='', error_messages={'unique': 'Esse WhatsApp já utilizou a análise gratuita.'}, max_length=20, validators=[django.core.validators.RegexValidator(message='Número de WhatsApp inválido. Use o formato: (34) 99999-9999', regex='^(\\+?55\\s?)?(\\(?\\d{2}\\)?\\s?)?9?\\d{4}-?\\d{4}$')], verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='whatsapplead',
            name='normalized_whatsapp',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Somente dígitos para lookup', max_length=20, verbose_name='WhatsApp Normalizado'),
        ),
    ]
