# Generated by Django 4.2.30 on 2026-05-28 (Manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_alter_whatsapp_fields_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAnalysisLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('analysis_count', models.IntegerField(default=0, verbose_name='Analysis Count')),
                ('last_analysis_date', models.DateField(auto_now=True, verbose_name='Last Analysis Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'IP Analysis Limit',
                'verbose_name_plural': 'IP Analysis Limits',
            },
        ),
        migrations.AddField(
            model_name='whatsapplead',
            name='analysis_count',
            field=models.IntegerField(default=1, verbose_name='Número de Análises'),
        ),
    ]
