# Generated by Django 4.2.30 on 2026-05-26 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(choices=[('landing', 'Landing Page'), ('dashboard', 'Dashboard'), ('api', 'API')], default='landing', max_length=20)),
                ('is_public_test', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Search',
                'verbose_name_plural': 'Product Searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('competition_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('saturation_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('price_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('final_score', models.DecimalField(db_index=True, decimal_places=1, max_digits=3)),
                ('classification', models.CharField(choices=[('bad', 'Produto ruim'), ('risky', 'Arriscado'), ('good', 'Boa oportunidade'), ('excellent', 'Alta oportunidade')], max_length=30)),
                ('confidence_level', models.IntegerField(default=70)),
                ('summary', models.TextField()),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product_search', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='market.productsearch')),
            ],
            options={
                'verbose_name': 'Market Analysis',
                'verbose_name_plural': 'Market Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
