# Generated by Django 4.2.30 on 2026-05-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoLivreToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_type', models.CharField(blank=True, default='Bearer', max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('scope', models.TextField(blank=True, default='')),
                ('user_id_ml', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mercado Livre Token',
                'verbose_name_plural': 'Mercado Livre Tokens',
            },
        ),
    ]
