# Generated by Django 4.2.30 on 2026-05-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_mercadolivretoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleTrendsCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Whether cooldown is currently active')),
                ('started_at', models.DateTimeField(blank=True, help_text='When cooldown started', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When cooldown expires', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for cooldown (e.g., HTTP 429)')),
                ('request_count', models.IntegerField(default=0, help_text='Number of requests made during cooldown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Trends Cooldown',
                'verbose_name_plural': 'Google Trends Cooldown',
            },
        ),
        migrations.CreateModel(
            name='GoogleTrendsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_query', models.CharField(db_index=True, help_text='Lowercase, trimmed, normalized query for cache lookup', max_length=100)),
                ('original_query', models.CharField(help_text='Original query as submitted', max_length=100)),
                ('raw_data', models.JSONField(default=dict, help_text='Complete Google Trends response')),
                ('source', models.CharField(choices=[('google_trends_live', 'Google Trends Live'), ('google_trends_error', 'Google Trends Error')], default='google_trends_live', max_length=30)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this data was fetched from Google Trends')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this cached data expires (24 hours)')),
                ('last_error', models.TextField(blank=True, help_text='Last error message if fetch failed', null=True)),
                ('error_count', models.IntegerField(default=0, help_text='Number of consecutive errors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Trends Cache',
                'verbose_name_plural': 'Google Trends Cache',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['normalized_query', 'expires_at'], name='market_goog_normali_1234df_idx')],
            },
        ),
    ]
